# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e241fa68086eb89d2a02234de40718ca3816e52e5b72cd1558307c8e7ce8f26e02224ee4c7ff5d1438e2e39f0b8ff1854c894a63a015ac29607ce55838688185

test:
  secret_key_base: c488e9bc0ce3ce98b5c8c4709cb85a5d056c1c23f82f0cf2c3380f0921e72248f31cb6211caa91cdbe19e23d19577cb3661a5b3d27d820c5147d28cdd3b8e5a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
